<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
//use Symfony\Component\HttpFoundation\RedirectResponse;

/**
 * Implements hook_form_alter().
 */
function save_and_edit_form_alter(&$form, FormStateInterface $form_state) {
  //var_dump($form);die;
  $form['actions']['save_edit'] = [
      '#type' => 'submit',
      '#value' => t('Save & Edit'),
      '#name' => 'save_and_edit',
      '#submit' => [
        '::save',
        'save_and_edit_form_submit_redirect',
    ]
  ]; 
}

function save_and_edit_form_submit_redirect(&$form, FormStateInterface $form_state) {
  die('bok');
  $query = \Drupal::requestStack()->getCurrentRequest()->query;
  $destination = $query->get('destination');
  $entity = $form_state->getFormObject()->getEntity();
  $url = $entity->url() . "?destination=" . $destination;
  //var_dump($entity->url() . "?destination=" . $destination);
  // var_dump(get_class_methods($entity));
  // var_dump(Url::fromUserInput($url)  );
  //die;
  //header("Location: http://www.example.com/");
  //exit();
  //return new RedirectResponse(Url::fromUserInput($url));
  var_dump($entity->url());die;
  $form_state->setRedirectUrl(Url::fromUserInput($url));
  //return;
}