<?php

function bug_report_theme($existing, $type, $theme, $path) {
  return [
    'bug_report' => [
      'variables' => [
        'error_message'    => null,
        'success_message'  => null,
      ],
    ],
  ];
}

/**
 * Implements hook_mail()
 */
function bug_report_mail($key, &$message, $params) {
  switch ($key) {
    case 'custom_mail_sending_key':
      $message['subject'] = $params['subject'];
      $message['body'][] = $params['message'];
      break;
  }
}